name: trainings_and_assessments
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2771.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

<<<<<<< HEAD
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_screen.gif
    - assets/images/python.png
    - assets/icons/clock.png
    - assets/images/python.png
    - assets/icons/social_leaderboard.png
    - assets/icons/mcq.png
    - assets/icons/technical.png
    - assets/icons/notification_add.png
    - assets/images/start_assessment.gif
    - assets/images/shareinfo.png
    - assets/images/shareinfo_big.png
    - assets/images/shareinfo_medium.png
    - assets/icons/quit.png
    - assets/images/success_mcq.gif
    - assets/icons/back_arrow.png
    - assets/images/bottom_right.png
    - assets/images/top_right.png
    - assets/images/bottom_left.png
    - assets/images/aspirant.png
    - assets/images/aspirant_bottom_right.png
    - assets/images/profile.png
    - assets/images/allright.gif
    - assets/images/exit.gif
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
=======
  assets:
    - assets/images/confo.gif
    - assets/images/python.png
    - assets/images/error1.gif
    - assets/images/assessment.gif
    - assets/images/shareinfo.png
    - assets/images/leaderboard.gif
    - assets/images/unlock.png
>>>>>>> 6b4298cd5405b9db6acdaaeadb51c9cd8cd3f8fa
