name: trainings_and_assessments
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2771.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/confo.gif
    - assets/images/python.png
    - assets/images/error1.gif
    - assets/images/assessment.gif
    - assets/images/shareinfo.png
    - assets/images/leaderboard.gif
    - assets/images/unlock.png
