name: trainings_and_assessments
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.gif
    - assets/images/python.png
    - assets/icons/clock.png
    - assets/images/python.png
    - assets/icons/social_leaderboard.png
    - assets/icons/mcq.png
    - assets/icons/technical.png
    - assets/icons/notification_add.png
    - assets/images/start_assessment.gif
    - assets/images/shareinfo.png
    - assets/images/shareinfo_big.png
    - assets/images/shareinfo_medium.png
    - assets/icons/quit.png
    - assets/images/success_mcq.gif
    - assets/icons/back_arrow.png
    - assets/images/bottom_right.png
    - assets/images/top_right.png
    - assets/images/bottom_left.png
    - assets/images/aspirant.png
    - assets/images/aspirant_bottom_right.png
    - assets/images/profile.png
    - assets/images/allright.gif
    - assets/images/exit.gif
    - assets/images/confo.gif
    - assets/images/python.png
    - assets/images/error1.gif
    - assets/images/assessment.gif
    - assets/images/shareinfo.png
    - assets/images/leaderboard.gif
    - assets/images/unlock.png
    - assets/icons/data_exploration.png
    - assets/icons/filter.png

